// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVZmSooWmE-k76ERNCyIeZvpxbe15DiOM',
    appId: '1:233477451195:web:6c12b272098b6a43de289e',
    messagingSenderId: '233477451195',
    projectId: 'login-authentication-72729',
    authDomain: 'login-authentication-72729.firebaseapp.com',
    storageBucket: 'login-authentication-72729.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfRmNBQoECrWWOkg7WuWFYOJYIb4lvKE',
    appId: '1:233477451195:android:b6ebb28d1e69e185de289e',
    messagingSenderId: '233477451195',
    projectId: 'login-authentication-72729',
    storageBucket: 'login-authentication-72729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5U6iYN5SI7IxpVKeE80xu-H1nXJjTko',
    appId: '1:233477451195:ios:fa5218a62df0df79de289e',
    messagingSenderId: '233477451195',
    projectId: 'login-authentication-72729',
    storageBucket: 'login-authentication-72729.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5U6iYN5SI7IxpVKeE80xu-H1nXJjTko',
    appId: '1:233477451195:ios:fa5218a62df0df79de289e',
    messagingSenderId: '233477451195',
    projectId: 'login-authentication-72729',
    storageBucket: 'login-authentication-72729.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVZmSooWmE-k76ERNCyIeZvpxbe15DiOM',
    appId: '1:233477451195:web:4ab85673042ed456de289e',
    messagingSenderId: '233477451195',
    projectId: 'login-authentication-72729',
    authDomain: 'login-authentication-72729.firebaseapp.com',
    storageBucket: 'login-authentication-72729.appspot.com',
  );
}
